backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "linux_notes"
    label: "የሊኑክስ ትምህርቶች"
    folder: "_posts/linux"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "አርእስት", name: "title", widget: "string" }
      - { label: "የዩቲዩብ ሊንክ", name: "video_url", widget: "string", required: false }
      - { label: "ማስታወሻ", name: "body", widget: "markdown" }